version: "3.8"

services:
  backend:
    build:
      context: ./server
    image: chinedudazi/ai-chat-backend:latest
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CLIENT_ORIGIN: http://localhost:3000
    restart: unless-stopped

  frontend:
    build:
      context: ./client
    image: chinedudazi/ai-chat-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000
    restart: unless-stopped
