apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: chinedudazi/ai-chat-frontend
          ports:
            - containerPort: 80  # Changed to match NGINX default
          env:
            - name: REACT_APP_API_URL
              value: http://backend-service:5000
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80  # Updated to match actual container port
            initialDelaySeconds: 10
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  loadBalancerIP: 74.249.144.2  # Your static public IP from Azure
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80  # Match containerPort for NGINX
