name: Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE_GROUP: ${{ secrets.AZURE_RG }}
  CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend Docker image
      run: |
        docker build -t ${{ secrets.FRONTEND_IMAGE_NAME }} ./client
        docker push ${{ secrets.FRONTEND_IMAGE_NAME }}

    - name: Build and push backend Docker image
      run: |
        docker build -t ${{ secrets.BACKEND_IMAGE_NAME }} ./server
        docker push ${{ secrets.BACKEND_IMAGE_NAME }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set active subscription
      run: az account set --subscription ${{ env.SUBSCRIPTION_ID }}

    - name: Get AKS credentials
      run: |
        az aks get-credentials \
          --resource-group $RESOURCE_GROUP \
          --name $CLUSTER_NAME \
          --overwrite-existing

    - name: Deploy to AKS using kubectl
      run: |
        kubectl apply -f Kubernetes/frontend-deployment.yaml
        kubectl apply -f Kubernetes/backend-deployment.yaml

